# Generated by Django 5.2.8 on 2025-11-10 10:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Property Name')),
                ('address', models.TextField(verbose_name='Property Address')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_date', models.DateField(default=datetime.date.today, verbose_name='Valuation Date')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Report Number')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(blank=True, max_length=100, verbose_name='Bank Branch')),
                ('bank_address', models.TextField(blank=True, verbose_name='Bank Address')),
                ('bank_req_date', models.DateField(blank=True, null=True, verbose_name='Bank Request Date')),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, verbose_name='Bank Reference No')),
                ('borrower_name', models.CharField(max_length=100, verbose_name='Borrower Name')),
                ('borrower_address', models.TextField(blank=True, verbose_name='Borrower Address')),
                ('borrower_contact', models.CharField(blank=True, max_length=15, verbose_name='Contact Number')),
                ('borrower_pan', models.CharField(blank=True, max_length=15, verbose_name='PAN Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Valuation Report',
                'verbose_name_plural': 'Valuation Reports',
                'ordering': ['-val_date'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=20, verbose_name='Plot Number')),
                ('ropani', models.IntegerField(default=0, verbose_name='Ropani')),
                ('ana', models.IntegerField(default=0, verbose_name='Ana')),
                ('paisa', models.IntegerField(default=0, verbose_name='Paisa')),
                ('dam', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Dam')),
                ('bigha', models.IntegerField(default=0, verbose_name='Bigha')),
                ('kattha', models.IntegerField(default=0, verbose_name='Kattha')),
                ('dhur', models.IntegerField(default=0, verbose_name='Dhur')),
                ('area_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Area (Sq. Ft)')),
                ('market_rate_per_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Market Rate/Sq.Ft')),
                ('fair_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fair Market Value')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='report.property')),
            ],
            options={
                'verbose_name_plural': 'Land Plots',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('address', models.TextField(blank=True, verbose_name='Owner Address')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='Contact Number')),
                ('citizenship_number', models.CharField(blank=True, max_length=20, verbose_name='Citizenship Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='report.property')),
            ],
            options={
                'verbose_name_plural': 'Property Owners',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='valuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='report.valuation'),
        ),
        migrations.CreateModel(
            name='VisitingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100, verbose_name='Team Member Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_teams', to='report.valuation')),
            ],
            options={
                'verbose_name': 'Visiting Team Member',
            },
        ),
    ]
