# Generated by Django 5.2.8 on 2025-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['plot_number'], 'verbose_name_plural': 'Land Plots'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='visitingteam',
            options={'verbose_name': 'Visiting Team Member', 'verbose_name_plural': 'Visiting Team Members'},
        ),
        migrations.AddField(
            model_name='owner',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='plot',
            name='area_sqmt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Area (Sq. M)'),
        ),
        migrations.AddField(
            model_name='plot',
            name='east_boundary',
            field=models.CharField(blank=True, max_length=100, verbose_name='East Boundary'),
        ),
        migrations.AddField(
            model_name='plot',
            name='gov_rate_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Government Rate/Sq.Ft'),
        ),
        migrations.AddField(
            model_name='plot',
            name='gov_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Government Value'),
        ),
        migrations.AddField(
            model_name='plot',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Market Value'),
        ),
        migrations.AddField(
            model_name='plot',
            name='north_boundary',
            field=models.CharField(blank=True, max_length=100, verbose_name='North Boundary'),
        ),
        migrations.AddField(
            model_name='plot',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='plot',
            name='sheet_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sheet Number'),
        ),
        migrations.AddField(
            model_name='plot',
            name='south_boundary',
            field=models.CharField(blank=True, max_length=100, verbose_name='South Boundary'),
        ),
        migrations.AddField(
            model_name='plot',
            name='west_boundary',
            field=models.CharField(blank=True, max_length=100, verbose_name='West Boundary'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('forest', 'Forest'), ('other', 'Other')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='property',
            name='ward_no',
            field=models.IntegerField(default=1, verbose_name='Ward Number'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='borrower_citizenship',
            field=models.CharField(blank=True, max_length=20, verbose_name='Citizenship Number'),
        ),
        migrations.AddField(
            model_name='visitingteam',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitingteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
